const mangas = [
    {
        id: 1,
        title: "Jujutsu Kaisen",
        image: "https://upload.wikimedia.org/wikipedia/pt/4/4b/Jujutsu_Kaisen_Cover.png",
        category: "Genre",
        subCategory: "Ação",
        author: "Gege Akutami",
        description: "Yuji Itadori, um adolescente, entra no mundo da feitiçaria.",
        yearPubli: "2021",
        status: "EM ANDAMENTO",
        demographic: "Shonen",
        tags: ["Ação", "Sobrenatural", "Terror"],
        saved: 0, // Contador de vezes salvo
        imagesList: [
            "https://criticalhits.com.br/wp-content/uploads/2021/04/jujutsu-kaisen-wallpaper-smartphone-09.jpg",
            "https://wallpapers.com/images/hd/itadori-hand-jujutsu-kaisen-iphone-483xqcsa46culk5s.jpg",
            "https://i.pinimg.com/736x/fa/8b/5a/fa8b5ae4ac6f2398b4e0cccdfcf80983.jpg",
            "https://wallpapers.com/images/hd/sleeping-itadori-and-sukuna-reflection-jujutsu-kaisen-phone-iq0fzvcstqnjguj6.jpg",
            "https://wallpaper4k.top/wp-content/uploads/2024/02/Fundo-de-Tela-Jujutsu-Kaisen-4k-para-Celular-Samsung-473x1024.jpg",
            "https://wallpapers.com/images/hd/sukuna-markings-yuji-itadori-jujutsu-kaisen-phone-jcnto771g11t36s8.jpg",
            "https://pbs.twimg.com/media/E12nRHkXIAMjmRO?format=jpg&name=large",
            "https://wallpapers.com/images/hd/minimalist-yuji-itadori-fanart-jujutsu-kaisen-phone-04anu0a01q2hjzoh.jpg",
            "https://wallpaper4k.top/wp-content/uploads/2024/02/Papel-de-Parede-4k-Jujutsu-Kaisen-Smartphone-473x1024.jpg",
        ],
    },
    {
        id: 2,
        title: "One Piece",
        image: "https://upload.wikimedia.org/wikipedia/pt/f/ff/One_Piece_vol._01.jpg",
        category: "Genre",
        subCategory: "Aventura",
        author: "Eiichiro Oda",
        description: "As aventuras de Monkey D. Luffy para encontrar o tesouro One Piece.",
        yearPubli: "2021",
        status: "Em andamento",
        demographic: "Shonen",
        tags: ["Aventura", "Comédia", "Fantasia"],
        saved: 0, // Contador de vezes salvo
    },
    {
        id: 3,
        title: "Kaguya-sama: Love is War",
        image: "https://upload.wikimedia.org/wikipedia/pt/5/5a/Capa_do_d%C3%A9cimo_volume_do_mang%C3%A1_Kaguya-sama.jpg",
        category: "Demographic",
        subCategory: "Comédia Romântica",
        author: "Aka Akasaka",
        description: "Dois gênios apaixonados competem para fazer o outro confessar primeiro.",
        yearPubli: "2021",
        status: "FINALIZADO",
        demographic: "Seinen",
        tags: ["Romance", "Comédia", "Psicológico"],
        saved: 0, // Contador de vezes salvo
    },
    {
        id: 4,
        title: "Attack on Titan",
        image: "https://upload.wikimedia.org/wikipedia/pt/e/e7/SnK_Volume1.png",
        category: "Genre",
        subCategory: "Ação",
        author: "Hajime Isayama",
        description: "Humanos enfrentam gigantes devoradores em um mundo pós-apocalíptico.",
        yearPubli: "2021",
        status: "FINALIZADO",
        demographic: "Shonen",
        tags: ["Ação", "Drama", "Sobrenatural"],
        saved: 0, // Contador de vezes salvo
    },
    {
        id: 5,
        title: "My Hero Academia",
        image: "https://upload.wikimedia.org/wikipedia/pt/5/5a/Boku_no_Hero_Academia_Volume_1.png",
        category: "Genre",
        subCategory: "Ação",
        author: "Kohei Horikoshi",
        description: "Izuku Midoriya tenta se tornar o maior herói do mundo.",
        yearPubli: "2021",
        status: "Em andamento",
        demographic: "Shonen",
        tags: ["Ação", "Aventura", "Fantasia"],
        saved: 0, // Contador de vezes salvo
    },
    {
        id: 6,
        title: "Death Note",
        image: "https://upload.wikimedia.org/wikipedia/pt/c/c0/Death_Note_vol._01.jpg",
        category: "Theme",
        subCategory: "Mistério",
        author: "Tsugumi Ohba",
        description: "Um estudante encontra um caderno que permite matar qualquer pessoa.",
        yearPubli: "2021",
        status: "FINALIZADO",
        demographic: "Shonen",
        tags: ["Mistério", "Suspense", "Psicológico"],
        saved: 0, // Contador de vezes salvo
    },
    {
        id: 7,
        title: "Tokyo Ghoul",
        image: "https://upload.wikimedia.org/wikipedia/pt/6/65/Tokyo_Ghoul_volume_1.jpg",
        category: "Theme",
        subCategory: "Horror",
        author: "Sui Ishida",
        description: "Ken Kaneki vira meio-ghoul após um encontro mortal.",
        yearPubli: "2021",
        status: "FINALIZADO",
        demographic: "Seinen",
        tags: ["Horror", "Sobrenatural", "Drama"],
        saved: 0, // Contador de vezes salvo
    },
    {
        id: 8,
        title: "Naruto",
        image: "https://upload.wikimedia.org/wikipedia/pt/d/d2/Naruto_vol._01.jpg",
        category: "Genre",
        subCategory: "Ação",
        author: "Masashi Kishimoto",
        description: "Naruto Uzumaki, um jovem ninja, busca reconhecimento e se tornar Hokage.",
        yearPubli: "2021",
        status: "FINALIZADO",
        demographic: "Shonen",
        tags: ["Ação", "Aventura", "Fantasia"],
        saved: 0, // Contador de vezes salvo
    },
    {
        id: 9,
        title: "Bleach",
        image: "https://upload.wikimedia.org/wikipedia/pt/4/45/Bleach_vol._01.jpg",
        category: "Genre",
        subCategory: "Ação",
        author: "Tite Kubo",
        description: "Ichigo Kurosaki ganha poderes de shinigami e protege os vivos dos Hollows.",
        yearPubli: "2021",
        status: "FINALIZADO",
        demographic: "Shonen",
        tags: ["Ação", "Sobrenatural", "Aventura"],
        saved: 0, // Contador de vezes salvo
    },
    {
        id: 10,
        title: "Hunter x Hunter",
        image: "https://upload.wikimedia.org/wikipedia/pt/6/63/Hunter_x_Hunter_Volume_1.JPG",
        category: "Genre",
        subCategory: "Aventura",
        author: "Yoshihiro Togashi",
        description: "Gon Freecss embarca em uma jornada para se tornar um Hunter e encontrar seu pai.",
        yearPubli: "2021",
        status: "Em Hiato",
        demographic: "Shonen",
        tags: ["Aventura", "Ação", "Fantasia"],
        saved: 0, // Contador de vezes salvo
    }
];

export default mangas;